In [1]:
# from IPython.display import Image
# Image(url='https://miro.medium.com/max/844/1*MyKDLRda6yHGR_8kgVvckg.png')

In [2]:
# # Importing the essential Libraries
import pandas as pd
# import numpy as np
import os

In [3]:
pwd

'C:\\Users\\Gaurav Kumar Singh'

In [35]:
# # Reading the Dataset
# # df = pd()
df = pd.read_csv("customer_churn_large_dataset.csv")
df.head()

CustomerID        Name  Age  Gender     Location  \
0           1  Customer_1   63    Male  Los Angeles   
1           2  Customer_2   62  Female     New York   
2           3  Customer_3   24  Female  Los Angeles   
3           4  Customer_4   36  Female        Miami   
4           5  Customer_5   46  Female        Miami   

   Subscription_Length_Months  Monthly_Bill  Total_Usage_GB  Churn  
0                          17         73.36             236      0  
1                           1         48.76             172      0  
2                           5         85.47             460      0  
3                           3         97.94             297      1  
4                          19         58.14             266      0

In [36]:
df.shape

(100000, 9)

In [37]:
df.columns

Index(['CustomerID', 'Name', 'Age', 'Gender', 'Location',
       'Subscription_Length_Months', 'Monthly_Bill', 'Total_Usage_GB',
       'Churn'],
      dtype='object')

In [38]:
df.dtypes

CustomerID                      int64
Name                           object
Age                             int64
Gender                         object
Location                       object
Subscription_Length_Months      int64
Monthly_Bill                  float64
Total_Usage_GB                  int64
Churn                           int64
dtype: object

In [40]:
# Printing Unique Values of the categorical variables
print(df['Gender'].unique())
print(df['Location'].unique())
print(df['Subscription_Length_Months'].unique())
print(df['Total_Usage_GB'].unique())
print(df['Churn'].unique())

['Male' 'Female']
['Los Angeles' 'New York' 'Miami' 'Chicago' 'Houston']
[17  1  5  3 19 15 10 12 20 13  8 23  2  4 18  9 14 16  6  7 24 22 11 21]
[236 172 460 297 266 456 269 396 150 383 442 295 148 239 233 231 198 354
 429 243 270 389 226 393  89 183 135 185 151 115 194 278 423 202 495 162
 101 294 122 305 212 220 253 411 447 218 221 166  64  67 391 232 298 334
 326 459 371 299 376 214 329  50 444 113  76 134 184 319 235  85 332  73
 369 308 446 321  83 114 296 102 215 169 225 140  84 463 402 468 375 366
 404 471 204 320 178 149 361 304 281 177 117 137 322 427 403 237 439 336
 344 288 257 196 365 419 111 192 244 287 395 213 109 286 283 230 491 274
 335 462 407 126 199 351 261 496 480 400 303 197 181 474 348 112 457  54
 397 100 318 242 327 476 256 241 466 438  51 165 120 493  59 188 339 167
 301 209 311 190 345 284 390  72 258 358 136 280  55 309 388  52 478 401
 472  65 163 488 497  71 216 229 271 223 263 255 145 203 372 443 306 307
 386 448 377 482 324 357 187 394 123 106  80 211  

In [41]:
# Checking if there are null values or not
df.isnull().sum()

CustomerID                    0
Name                          0
Age                           0
Gender                        0
Location                      0
Subscription_Length_Months    0
Monthly_Bill                  0
Total_Usage_GB                0
Churn                         0
dtype: int64

In [42]:
df.describe()

CustomerID            Age  Subscription_Length_Months  \
count  100000.000000  100000.000000               100000.000000   
mean    50000.500000      44.027020                   12.490100   
std     28867.657797      15.280283                    6.926461   
min         1.000000      18.000000                    1.000000   
25%     25000.750000      31.000000                    6.000000   
50%     50000.500000      44.000000                   12.000000   
75%     75000.250000      57.000000                   19.000000   
max    100000.000000      70.000000                   24.000000   

        Monthly_Bill  Total_Usage_GB          Churn  
count  100000.000000   100000.000000  100000.000000  
mean       65.053197      274.393650       0.497790  
std        20.230696      130.463063       0.499998  
min        30.000000       50.000000       0.000000  
25%        47.540000      161.000000       0.000000  
50%        65.010000      274.000000       0.000000  
75%        82.640000      387.000000       1.000000  
max       100.000000      500.000000       1.000000

In [43]:
df.head()

CustomerID        Name  Age  Gender     Location  \
0           1  Customer_1   63    Male  Los Angeles   
1           2  Customer_2   62  Female     New York   
2           3  Customer_3   24  Female  Los Angeles   
3           4  Customer_4   36  Female        Miami   
4           5  Customer_5   46  Female        Miami   

   Subscription_Length_Months  Monthly_Bill  Total_Usage_GB  Churn  
0                          17         73.36             236      0  
1                           1         48.76             172      0  
2                           5         85.47             460      0  
3                           3         97.94             297      1  
4                          19         58.14             266      0

In [74]:
# Including only Potential Predictors as independent varibles
final_dataset = df[['Age','Gender','Location','Subscription_Length_Months','Monthly_Bill','Total_Usage_GB','Churn']]


In [75]:
final_dataset.head()

Age  Gender     Location  Subscription_Length_Months  Monthly_Bill  \
0   63    Male  Los Angeles                          17         73.36   
1   62  Female     New York                           1         48.76   
2   24  Female  Los Angeles                           5         85.47   
3   36  Female        Miami                           3         97.94   
4   46  Female        Miami                          19         58.14   

   Total_Usage_GB  Churn  
0             236      0  
1             172      0  
2             460      0  
3             297      1  
4             266      0

In [76]:
# Converting the categorical variables into numerical and avoiding Dummy Varibale Trap
final_dataset = pd.get_dummies(final_dataset, drop_first=True)

In [77]:
final_dataset.head()

Age  Subscription_Length_Months  Monthly_Bill  Total_Usage_GB  Churn  \
0   63                          17         73.36             236      0   
1   62                           1         48.76             172      0   
2   24                           5         85.47             460      0   
3   36                           3         97.94             297      1   
4   46                          19         58.14             266      0   

   Gender_Male  Location_Houston  Location_Los Angeles  Location_Miami  \
0            1                 0                     1               0   
1            0                 0                     0               0   
2            0                 0                     1               0   
3            0                 0                     0               1   
4            0                 0                     0               1   

   Location_New York  
0                  0  
1                  1  
2                  0  
3                  0  
4                  0

In [78]:
# import seaborn as sns

In [79]:
# sns.pairplot(final_dataset)

In [80]:
# import matplotlib.pyplot as plt
# %matplotlib inline

In [81]:
# Plotting The Correlations between all the features
# corrmat = final_dataset.corr()
# top_corr_features = corrmat.index
# plt.figure(figsize=(20,20))
# sns.heatmap(final_dataset[top_corr_features].corr(), annot=True, cmap='RdYlGn')

In [82]:
# final_dataset.head()

In [83]:
# Splitting the Dataset into Dependent and Independent Variables
X = final_dataset.iloc[:, [0,1,2,3,4,5]]
y = final_dataset.iloc[:, 6].values

In [84]:
X.head()

Age  Subscription_Length_Months  Monthly_Bill  Total_Usage_GB  Churn  \
0   63                          17         73.36             236      0   
1   62                           1         48.76             172      0   
2   24                           5         85.47             460      0   
3   36                           3         97.94             297      1   
4   46                          19         58.14             266      0   

   Gender_Male  
0            1  
1            0  
2            0  
3            0  
4            0

In [85]:
y

array([0, 0, 0, ..., 0, 0, 0], dtype=uint8)

In [86]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2, random_state = 42)

In [87]:
# Standardizing the Dataset
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [88]:
print(X_train)

[[ 0.65344669 -1.08272837  0.96025455 -0.53377381  1.00355632 -0.99553497]
 [-1.04827574  1.66388226  0.83962354 -0.27325726  1.00355632  1.00448506]
 [ 0.84979927 -0.07081919 -0.63217363 -1.62947581  1.00355632  1.00448506]
 ...
 [ 1.63520963 -1.51640373  0.55188892  0.35504739  1.00355632  1.00448506]
 [ 0.71889755 -0.07081919  1.19212316  0.30907388  1.00355632  1.00448506]
 [-1.17917747  0.65197308  0.26365992  0.46231891 -0.99645628 -0.99553497]]


In [89]:
## Feature Importance
from sklearn.ensemble import ExtraTreesRegressor
model = ExtraTreesRegressor()
model.fit(X,y)

ExtraTreesRegressor()

In [90]:
print(model.feature_importances_)

[0.22366034 0.1684649  0.30965744 0.29532181 0.00032258 0.00257293]


In [91]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier()
rf.fit(X_train,y_train)

RandomForestClassifier()

In [92]:
y_pred = rf.predict(X_test)

In [93]:
from sklearn.metrics import accuracy_score, confusion_matrix
cm = confusion_matrix(y_test,y_pred)
print(cm)
print(accuracy_score(y_test,y_pred))

[[15790   164]
 [ 4006    40]]
0.7915


In [94]:
# pickling the Model
import pickle
file = open('Customer_Churn_Prediction.pkl', 'wb')
pickle.dump(rf, file)

In [114]:
# import pandas as pd
# import ipywidgets as widgets
# import pickle
# from IPython.display import display
# # from sklearn.preprocessing import LabelEncoder

# # # Create a label encoder
# # label_encoder = LabelEncoder()

# # # Apply label encoding to the 'Customer ID' feature
# # data['Customer ID'] = label_encoder.fit_transform(data['Customer ID'])


# # Load your dataset (replace 'dataset.csv' with your data)
# df = pd.read_csv("customer_churn_large_dataset.csv")

# # Create input widgets
# # customer_id = widgets.IntText(description='CustomerID:')
# customer_name = widgets.Text(description='Name:')
# customer_age = widgets.IntSlider(description='Age:', min=18, max=100, value=30)
# customer_gender = widgets.RadioButtons(description='Gender:', options=['Male', 'Female'])
# customer_location = widgets.Text(description='Location:')
# subscription_length = widgets.IntSlider(description='Subscription_Length_Months:', min=1, max=36, value=12)
# monthly_bill = widgets.FloatText(description='Monthly_Bill:')
# total_usage_gb = widgets.FloatText(description='Total_Usage_GB:')

# # Button to predict churn
# predict_button = widgets.Button(description='Predict Churn')
# output_label = widgets.Label()
# # model = joblib.load('Customer_Churn_Prediction.pkl')
# # with open('Customer_Churn_Prediction.pkl', 'wb') as model_file:
# #     model = pickle.load(model_file)
# file = open('Customer_Churn_Prediction.pkl', 'wb')
# pickle.dump(rf, file)

# # Define your machine learning model (replace 'model' with your trained model)
# def predict_churn(b):
#     # Get input values from widgets
#     data = {
# #         'CustomerID': [customer_id.value],
#         'Name': [customer_name.value],
#         'Age': [customer_age.value],
#         'Gender': [customer_gender.value],
#         'Location': [customer_location.value],
#         'Subscription_Length_Months': [subscription_length.value],
#         'Monthly_Bill': [monthly_bill.value],
#         'Total_Usage_GB': [total_usage_gb.value]
#     }

#     # Create a DataFrame from input data
#     X_test= pd.DataFrame(data)

#     # Make a prediction using your trained model
#     prediction = rf.predict(X_test)  # Replace 'model' with your trained model

#     # Show the prediction result
#     if prediction[0] == 1:
#         output_label.value = "Churn: Yes"
#     else:
#         output_label.value = "Churn: No"

# predict_button.on_click(predict_churn)

# # Display widgets and output
# input_widgets = widgets.VBox([
# #     customer_id,
#     customer_name,
#     customer_age,
#     customer_gender,
#     customer_location,
#     subscription_length,
#     monthly_bill,
#     total_usage_gb,
#     predict_button
# ])

# output_widgets = widgets.VBox([
#     widgets.Label('Prediction Result:'),
#     output_label
# ])

# display(widgets.HBox([input_widgets, output_widgets]))


ValueError: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- CustomerID
